apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: i000uztr7-dotnet-basic 
  janus-idp.io/tekton: i000uztr7-dotnet-basic
  backstage.io/kubernetes-id: i000uztr7-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i000uztr7-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml